[platformio]
src_dir = .
include_dir = .

[env:esp32-s3-zero]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200
build_src_filter =
    +<main.cpp>
    +<analysis/*.cpp>
    +<communication/*.cpp>
    +<config/*.cpp>
    +<safety/*.cpp>
    +<telemetry/*.cpp>
    +<web/*.cpp>
build_flags =
    -D BOARD_ESP32_S3_ZERO
    -D PEGASUS_REV_A0

[env:xiao-esp32-s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
build_src_filter =
    +<main.cpp>
    +<analysis/*.cpp>
    +<communication/*.cpp>
    +<config/*.cpp>
    +<safety/*.cpp>
    +<telemetry/*.cpp>
    +<web/*.cpp>
build_flags =
    -D BOARD_XIAO_ESP32_S3
    -D PEGASUS_REV_A0
